![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Créez vos premiers arrays avec Numpy - Enoncé

Tout au long de ce cours, nous allons nous mettre dans la peau d’une personne travaillant  dans un service data au sein d'une banque. Plus précisément, vous travaillez pour la filière gérant les différents prêts. L’objectif sera d’utiliser les connaissances acquises sur les librairies Python pour aider l’agence dans différentes tâches.

Pour cette première tâche, nous avons à notre disposition les revenus de 10 clients de notre banque. Vous aurez à utiliser les différentes manipulations présentées dans ce chapitre pour sélectionner certains revenus selon une condition spécifique et effectuer diverses opérations.

* version 0.0.3
* last update 2022-08-01
* author Alexandre Gazagnes

Importons numpy : 

In [2]:
import numpy as np 

Considérons les revenus mensuels suivants :

In [3]:
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

A partir de ces revenus, créez un array que vous nommerez `revenus` :

In [4]:
revenus = np.array(liste)
revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

Maintenant, créez un nouvel array `haut_revenus` dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€ :

In [5]:
haut_revenus = revenus[revenus >= 3000]
haut_revenus

array([3000, 5000])

Il est à présent temps de calculer quelques indicateurs :
- calculez dans un premier temps la somme des revenus **annuelle**. Pour rappel, les revenus listés ci dessus sont mensuels.
- calculez ensuite la moyenne des revenus des 10 clients

In [8]:
somme = (revenus*12).sum()
somme

248064

In [12]:
moyenne = (revenus).mean()
moyenne

2087.2

Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel. Effectuez cette modification au sein de votre array revenus.

In [11]:
revenus[revenus == 1400] = 1600
revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1600, 1200, 1100, 1300])

Félicitation pour être arrivé au bout !

Si vous avez rencontré certains problèmes : aucune inquiétude :) Vous trouverez la correction dans le cours!